steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.vcp-insider-daily
      - -t
      - us-west1-docker.pkg.dev/gmailpj-357912/tob/vcp-insider-daily:latest
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-west1-docker.pkg.dev/gmailpj-357912/tob/vcp-insider-daily:latest
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Updating job: vcp-insider-daily"
        gcloud run jobs update vcp-insider-daily --region=us-west1 \
          --image=us-west1-docker.pkg.dev/gmailpj-357912/tob/vcp-insider-daily:latest

images:
  - us-west1-docker.pkg.dev/gmailpj-357912/tob/vcp-insider-daily:latest
