steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.tdnet-load-parallel
      - -t
      - us-west1-docker.pkg.dev/gmailpj-357912/tdnet/tdnet-load-parallel:latest
      - .

images:
  - us-west1-docker.pkg.dev/gmailpj-357912/tdnet/tdnet-load-parallel:latest
