steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.tdnet-load-recovery
      - -t
      - us-west1-docker.pkg.dev/gmailpj-357912/tdnet/tdnet-load-recovery:latest
      - .

images:
  - us-west1-docker.pkg.dev/gmailpj-357912/tdnet/tdnet-load-recovery:latest
