steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-west1-docker.pkg.dev/gmailpj-357912/fred-mcp/fred-mcp:latest
      - -f
      - docker/Dockerfile.fred-mcp
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-west1-docker.pkg.dev/gmailpj-357912/fred-mcp/fred-mcp:latest

images:
  - us-west1-docker.pkg.dev/gmailpj-357912/fred-mcp/fred-mcp:latest
