steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.aws-cost-explorer-mcp
      - -t
      - us-west1-docker.pkg.dev/gmailpj-357912/tools/aws-cost-explorer-mcp:latest
      - .

images:
  - us-west1-docker.pkg.dev/gmailpj-357912/tools/aws-cost-explorer-mcp:latest
