steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.build-monthly-extractor
      - -t
      - us-west1-docker.pkg.dev/gmailpj-357912/tools/build-monthly-extractor:latest
      - .

images:
  - us-west1-docker.pkg.dev/gmailpj-357912/tools/build-monthly-extractor:latest
