steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.dividend-date-load
      - -t
      - us-west1-docker.pkg.dev/gmailpj-357912/stock/dividend-date-load:latest
      - .

images:
  - us-west1-docker.pkg.dev/gmailpj-357912/stock/dividend-date-load:latest
