steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.jquants-fin-summary
      - -t
      - us-west1-docker.pkg.dev/gmailpj-357912/jquants/jquants-fin-summary:latest
      - .

images:
  - us-west1-docker.pkg.dev/gmailpj-357912/jquants/jquants-fin-summary:latest
