steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.download-monthly
      - -t
      - gcr.io/gmailpj-357912/download-monthly:latest
      - .

images:
  - gcr.io/gmailpj-357912/download-monthly:latest
