steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - docker/Dockerfile.type-c-investigate
      - -t
      - us-west1-docker.pkg.dev/gmailpj-357912/tools/type-c-investigate:latest
      - .

images:
  - us-west1-docker.pkg.dev/gmailpj-357912/tools/type-c-investigate:latest
