-- V_CONSENSUS_MERGED: QUICK優先・IFIS補完マージVIEW
-- TARGET列廃止、5項目対応
-- 実行日: 2026-05-05

CREATE OR REPLACE VIEW `gmailpj-357912.STOCK.V_CONSENSUS_MERGED` AS
WITH quick_latest AS (
  SELECT
    TICKER, FY, QUARTER, DATAAT,
    REVENUE, OP_PROFIT, ORD_PROFIT, NET_PROFIT, EPS
  FROM `gmailpj-357912.STOCK.CONSENSUS`
  WHERE SOURCE = 'QUICK'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TICKER, FY, QUARTER
    ORDER BY DATAAT DESC
  ) = 1
),
ifis_latest AS (
  SELECT
    TICKER, FY, QUARTER, DATAAT,
    ORD_PROFIT
  FROM `gmailpj-357912.STOCK.CONSENSUS`
  WHERE SOURCE = 'IFIS'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TICKER, FY, QUARTER
    ORDER BY DATAAT DESC
  ) = 1
)
SELECT
  COALESCE(q.TICKER, i.TICKER) AS TICKER,
  COALESCE(q.FY, i.FY) AS FY,
  COALESCE(q.QUARTER, i.QUARTER) AS QUARTER,
  COALESCE(q.DATAAT, i.DATAAT) AS DATAAT,
  q.REVENUE,
  q.OP_PROFIT,
  COALESCE(q.ORD_PROFIT, i.ORD_PROFIT) AS ORD_PROFIT,
  q.NET_PROFIT,
  q.EPS
FROM quick_latest q
FULL OUTER JOIN ifis_latest i
  ON q.TICKER = i.TICKER
  AND q.FY = i.FY
  AND q.QUARTER = i.QUARTER;
